### PR TITLE
Add cmake helpers to cmake module path

### PR DESCRIPTION
**Pull request by HackingPheasant**
Overall this is more of a just Quality of Life improvement as it just removes visual cruft when including each CMake helper

### CODE REVIEW

**Comment by lefticus** [comment]
@ddalcino @aminya do you have an opinion on this one?

**Review by aminya — CHANGES_REQUESTED** [review]
I would prefer the current behavior since the path to the CMake files is exactly as they are on the file system. If someone doesn't know what `CMAKE_MODULE_PATH` is, they might be confused for some time.

**Comment by ddalcino** [comment]
> @ddalcino @aminya do you have an opinion on this one?

I really liked this PR, and I like to do this in my own projects. I forgot to give it an approving review ...

> I would prefer the current behavior since the path to the CMake files is exactly as they are on the file system. If someone doesn't know what CMAKE_MODULE_PATH is, they might be confused for some time.

... but that's a really good point, and I think @aminya is right.

**Comment by lefticus** [comment]
I'll admit I did not actually know what it was doing at first either, and I've been using CMake for awhile now. I'm also inclined to the simple direct paths, as @aminya says.

Thank you @HackingPheasant , we appreciate your submission, but will not be merging it right now, as we think it could cause confusion for new users of CMake, and that outweighs the benefits.

**Comment by HackingPheasant** [comment]
That's all good. I found it useful when I needed to include a cmake file in a CMakeLists.txt that was a few directories deep, meaning I didn't need to traverse a few directories and keep that path updated and correct if I ever did move stuff around.

And just to leave this info documented here if you ever change your mind you can have multiple paths listed like so (take from my personal project)

```
set(CMAKE_MODULE_PATH "${PROJECT_SOURCE_DIR}/cmake;${PROJECT_SOURCE_DIR}/cmake/3rd-party" ${CMAKE_MODULE_PATH})
```

**Comment by ddalcino** [comment]
> ```
> set(CMAKE_MODULE_PATH "${PROJECT_SOURCE_DIR}/cmake;${PROJECT_SOURCE_DIR}/cmake/3rd-party" ${CMAKE_MODULE_PATH})
> ```

Personally, I'd like to see this line of code in the top level CMakeLists.txt file, commented out, with comments describing what it does and how it can be used. Users who want to use it (like me) could simply uncomment and start using it; others can just ignore it.

**Pull request closed without merging**
