### PR TITLE
Added -extra-arg=-Wno-unknown-warning-option to clang-tidy

### PR DESCRIPTION
**Pull request by mo-xiaoming**
If `ENABLE_CLANG_TIDY=ON` and compiler is gcc, then those extra gcc warning flags trigger clang-tidy error `clang-diagnostic-unknown-warning-option`

```
error: unknown warning option '-Wduplicated-branches' [clang-diagnostic-unknown-warning-option]
error: unknown warning option '-Wduplicated-cond'; did you mean '-Wduplicate-enum'? [clang-diagnostic-unknown-warning-option]
error: unknown warning option '-Wlogical-op'; did you mean '-Wlong-long'? [clang-diagnostic-unknown-warning-option]
error: unknown warning option '-Wmisleading-indentation'; did you mean '-Wbinding-in-condition'? [clang-diagnostic-unknown-warning-option]
error: unknown warning option '-Wuseless-cast' [clang-diagnostic-unknown-warning-option]
```

### CODE REVIEW

**Comment by ddalcino** [comment]
This appears to fix the same problem addressed by PR #18.

Is it really a better solution to the problem?

**Comment by mo-xiaoming** [comment]
Hi @ddalcino,

I might miss something, but I was using a GCC, not AppleClang, I don't see how this two problem related.

To double check that, I applied the change form #18 

```diff
$ git diff
diff --git a/cmake/CompilerWarnings.cmake b/cmake/CompilerWarnings.cmake
index c0b442e..219465f 100644
--- a/cmake/CompilerWarnings.cmake
+++ b/cmake/CompilerWarnings.cmake
@@ -79,7 +79,7 @@ function(set_project_warnings project_name)
 
   if(MSVC)
     set(PROJECT_WARNINGS ${MSVC_WARNINGS})
-  elseif(CMAKE_CXX_COMPILER_ID STREQUAL "Clang")
+  elseif(CMAKE_CXX_COMPILER_ID MATCHES ".*Clang")
     set(PROJECT_WARNINGS ${CLANG_WARNINGS})
   else()
     set(PROJECT_WARNINGS ${GCC_WARNINGS})
diff --git a/cmake/Sanitizers.cmake b/cmake/Sanitizers.cmake
index 9faf76f..fd21cd6 100644
--- a/cmake/Sanitizers.cmake
+++ b/cmake/Sanitizers.cmake
@@ -1,7 +1,7 @@
 function(enable_sanitizers project_name)
 
-  if(CMAKE_CXX_COMPILER_ID STREQUAL "GNU" OR CMAKE_CXX_COMPILER_ID STREQUAL
-                                             "Clang")
+  if(CMAKE_CXX_COMPILER_ID STREQUAL "GNU" OR CMAKE_CXX_COMPILER_ID MATCHES
+                                             ".*Clang")
     option(ENABLE_COVERAGE "Enable coverage reporting for gcc/clang" FALSE)
 
     if(ENABLE_COVERAGE)
diff --git a/test/CMakeLists.txt b/test/CMakeLists.txt
index 6644f18..0b55b10 100644
--- a/test/CMakeLists.txt
+++ b/test/CMakeLists.txt
@@ -8,6 +8,7 @@ endif()
 
 add_library(catch_main STATIC catch_main.cpp)
 target_link_libraries(catch_main PUBLIC CONAN_PKG::catch2)
+target_link_libraries(catch_main PRIVATE project_options)
 
 add_executable(tests tests.cpp)
 target_link_libraries(tests PRIVATE project_warnings project_options
```

Then ran with `clang-tidy` enabled, and error still occured, so #18 doesn't fix this issue

```
$ cmake -Bbuild -DENABLE_CLANG_TIDY=ON
-- The CXX compiler identification is GNU 9.2.1
-- Check for working CXX compiler: /usr/bin/g++
-- Check for working CXX compiler: /usr/bin/g++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Setting build type to 'RelWithDebInfo' as none was specified.
using ccache
-- Conan: checking conan executable
-- Conan: Found program …/pyenv/bin/conan
-- Conan: Version found Conan version 1.22.2

-- Conan: Adding bincrafters remote repository (https://api.bintray.com/conan/bincrafters/public-conan)
-- Conan: Automatic detection of conan settings from cmake
-- Conan: Settings= -s;build_type=RelWithDebInfo;-s;compiler=gcc;-s;compiler.version=9;-s;compiler.libcxx=libstdc++11
-- Conan: checking conan executable
-- Conan: Found program …/pyenv/bin/conan
-- Conan: Version found Conan version 1.22.2

-- Conan executing: …/pyenv/bin/conan install . -s build_type=RelWithDebInfo -s compiler=gcc -s compiler.version=9 -s compiler.libcxx=libstdc++11 -g=cmake --build=missing
Configuration:
[settings]
arch=x86_64
arch_build=x86_64
build_type=RelWithDebInfo
compiler=gcc
compiler.libcxx=libstdc++11
compiler.version=9
os=Linux
os_build=Linux
[options]
[build_requires]
[env]

conanfile.txt: Installing package
Requirements
    catch2/2.11.0 from 'conan-center' - Cache
    docopt.cpp/0.6.2 from 'conan-center' - Cache
    fmt/6.0.0 from 'conan-center' - Cache
    spdlog/1.5.0 from 'conan-center' - Cache
Packages
    catch2/2.11.0:5ab84d6acfe1f23c4fae0ab88f26e3a396351ac9 - Cache
    docopt.cpp/0.6.2:f54287fc3dbd09590f968b580bebb565ea4a4b17 - Cache
    fmt/6.0.0:f54287fc3dbd09590f968b580bebb565ea4a4b17 - Cache
    spdlog/1.5.0:12c8590eca64ca13d7eac957bde897f3a31c0f6e - Cache

catch2/2.11.0: Already installed!
docopt.cpp/0.6.2: Already installed!
fmt/6.0.0: Already installed!
spdlog/1.5.0: Already installed!
conanfile.txt: Generator cmake created conanbuildinfo.cmake
conanfile.txt: Generator txt created conanbuildinfo.txt
conanfile.txt: Generated conaninfo.txt
conanfile.txt: Generated graphinfo
WARN: spdlog/1.5.0: requirement fmt/6.1.2 overridden by your conanfile to fmt/6.0.0 
-- Conan: Loading conanbuildinfo.cmake
-- Conan: Adjusting output directories
-- Conan: Using cmake targets configuration
-- Library docopt found …/.conan/data/docopt.cpp/0.6.2/_/_/package/f54287fc3dbd09590f968b580bebb565ea4a4b17/lib/libdocopt.a
-- Library spdlog found …/.conan/data/spdlog/1.5.0/_/_/package/12c8590eca64ca13d7eac957bde897f3a31c0f6e/lib/libspdlog.a
-- Library pthread not found in package, might be system one
-- Library fmt found …/.conan/data/fmt/6.0.0/_/_/package/f54287fc3dbd09590f968b580bebb565ea4a4b17/lib/libfmt.a
-- Conan: Adjusting default RPATHs Conan policies
-- Conan: Adjusting language standard
-- Current conanbuildinfo.cmake directory: /home/mx/Documents/playground/cpp/cpp_starter_project/build
-- Conan: Compiler GCC>=5, checking major version 9
-- Conan: Checking correct version: 9
Building Tests. Be sure to check out test/constexpr_tests for constexpr testing
-- Configuring done
-- Generating done
-- Build files have been written to: …/cpp_starter_project/build


$ cmake --build build
Scanning dependencies of target catch_main
[ 10%] Building CXX object test/CMakeFiles/catch_main.dir/catch_main.cpp.o
[ 20%] Linking CXX static library ../lib/libcatch_main.a
[ 20%] Built target catch_main
Scanning dependencies of target tests
[ 30%] Building CXX object test/CMakeFiles/tests.dir/tests.cpp.o
error: unknown warning option '-Wduplicated-branches' [clang-diagnostic-unknown-warning-option]
error: unknown warning option '-Wduplicated-cond'; did you mean '-Wduplicate-enum'? [clang-diagnostic-unknown-warning-option]
error: unknown warning option '-Wlogical-op'; did you mean '-Wlong-long'? [clang-diagnostic-unknown-warning-option]
error: unknown warning option '-Wmisleading-indentation'; did you mean '-Wbinding-in-condition'? [clang-diagnostic-unknown-warning-option]
error: unknown warning option '-Wuseless-cast' [clang-diagnostic-unknown-warning-option]
16472 warnings and 5 errors generated.
Error while processing /home/mx/Documents/playground/cpp/cpp_starter_project/test/tests.cpp.
Suppressed 16476 warnings (16472 in non-user code, 4 NOLINT).
Use -header-filter=.* to display errors from all non-system headers. Use -system-headers to display errors from system headers as well.
Found compiler error(s).
test/CMakeFiles/tests.dir/build.make:62: recipe for target 'test/CMakeFiles/tests.dir/tests.cpp.o' failed
make[2]: *** [test/CMakeFiles/tests.dir/tests.cpp.o] Error 1
CMakeFiles/Makefile2:147: recipe for target 'test/CMakeFiles/tests.dir/all' failed
make[1]: *** [test/CMakeFiles/tests.dir/all] Error 2
Makefile:94: recipe for target 'all' failed
make: *** [all] Error 2
```

**Comment by ddalcino** [comment]
Please disregard my comment; I misunderstood the issue

**Comment by carlsonmark** [comment]
I was just about to submit the same PR. `-extra-arg=-Wno-unknown-warning-option` is a good idea in this case.

**Pull request merged**
