### PR TITLE
Minimal Qt example

### PR DESCRIPTION
**Pull request by alexallmont**
Hi Jason,

After your recent video I noticed a number of comments asking for Qt. This code contains a minimal CMake Qt app for OSX and Windows. It has a custom widget as the main frame and demonstrates the new-style signal connections using lambdas.

I've tested this on OSX, and in principle it should work on Windows but the QT_DIR is incorrect. Before fixing that though I wanted to check if this is something you actually wanted in your project! If so please let me know and I'll invest more time in it, and I can also look into getting Linux builds working.

Thanks
Alex

### CODE REVIEW

**Comment by lefticus** [comment]
It has been several years since I last used Qt, so I don't know the current best practices. Can you please collaborate with the PR #3 and come  to a conclusion for a single PR that has the best of both?

**Comment by alexallmont** [comment]
Thanks Jason, I'll chip in after work today.


Best wishes,

Alex

________________________________

**Comment by lefticus** [comment]
So we can delete this PR, correct? @alexallmont

**Comment by alexallmont** [comment]
Yes thanks @lefticus, closing this PR.

**Pull request closed without merging**
